services:
  devdot:
    build: .
    container_name: devdot
    environment:
      - USERNAME=${DEV_USER}
      - PASSWORD=${DEV_PASSWORD}
      - TZ=${TZ:-UTC}
    ports:
      - "${SSH_PORT}:22"
      - "${MOSH_PORTS:-62000-62100}:62000-62100/udp"  # Configurable Mosh ports
    volumes:
      - ${WORKSPACE_DIR}:/home/${DEV_USER}/workspace
      - ${HOST_SSH_DIR:-~/.ssh}:/home/${DEV_USER}/.ssh:ro  # Read-only mount of host SSH directory
      - ./dotfiles/tmux/.tmux.conf:/home/${DEV_USER}/.tmux.conf
      - ./dotfiles/helix:/home/${DEV_USER}/.config/helix
      - ./dotfiles/zsh/.zshrc:/home/${DEV_USER}/.zshrc
      - ./dotfiles/fzf/.fzf.zsh:/home/${DEV_USER}/.fzf.zsh
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined  # Needed for proper debugger support
    cap_add:
      - SYS_PTRACE  # Required for debugging tools
