theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
cursorline = true
color-modes = true
auto-pairs = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
